---
homebrew_taps:
  - caskroom/cask

homebrew_packages:
  - { name: ansible }
  - { name: cmake }
  - { name: brew-cask }
  - { name: fish }
  - { name: ghq }
  - { name: git }
  - { name: jq }
  - { name: libmagic }
  - { name: mysql }
  - { name: rbenv }
  - { name: peco }
  - { name: python }
  - { name: readline }
  - { name: rbenv }
  - { name: tmux }
  - { name: tree }
  - { name: wget }
  - { name: zsh }
  - { name: zsh-completions }

homebrew_cask_packages:
  - alfred
  - bettertouchtool
  - dockertoolbox
  - dropbox
  - firefox
  - intellij-idea
  - iterm2
  - karabiner
  - slack
  - vagrant
  - virtualbox
