---
# brew tap
- name: install taps of homebrew
  homebrew_tap: tap="{{ item }}" state=present
  with_items: homebrew_taps

# brew update
- name: update homebrew
  homebrew: update_homebrew=yes

# brew instal
- name: install homebrew packages
  homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
  with_items: homebrew_packages

# brew cask install
- name: update brew-cask
  homebrew: name=brew-cask state=latest
- name: install homebrew cask packages
  homebrew_cask: name="{{ item }}" state=present
  with_items: homebrew_cask_packages
